name: Nieuwe game
description: Een nieuwe game in het archief voorstellen
title: "Nieuwe game"
labels: "nieuw"
body:
  - type: textarea
    id: description
    attributes:
      label: Omschrijving
    validations:
      required: true
  - type: input
    id: uitgever_ontwikkelaar
    attributes:
      label: Uitgever/ontwikkelaar
    validations:
      required: false
  - type: input
    id: jaar_van_uitgave
    attributes:
      label: Jaar van uitgave
    validations:
      required: false
  - type: input
    id: download_archive
    attributes:
      label: Download (Archive.org)
      placeholder: "URL"
    validations:
      required: false