name: Aanpassing
description: Aanpassing of toevoeging aan pagina doen
title: "Aanpassing"
labels: "aanpassing"
body:
  - type: textarea
    id: description
    attributes:
      label: Omschrijving
    validations:
      required: true