name: Change
description: Aanpassing of toevoeging aan pagina doen
title: ""
labels: "aanpassing"
assignees: []
body:
  - type: textarea
    id: description
    attributes:
      label: Omschrijving
    validations:
      required: true